name: ğŸ› ï¸ Test Branch name checker workflow
on:
  pull_request:

jobs:
  test-branch-name:
    runs-on: ubuntu-latest
    name: ğŸƒ Run the action
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: ğŸ“¥ Checkout the code
        uses: actions/checkout@v4
      - uses: ./
        with:
          branch_pattern: 'feature|bug|chore|hotfix'
          comment_for_invalid_branch_name: 'ğŸ™ˆ Ups! This branch name is not following the standards!'
          fail_if_invalid_branch_name: 'false'